import webpack from 'webpack'
import webpackDevMiddleware from 'webpack-dev-middleware'
import MFS from 'memory-fs'
import chokidar from 'chokidar'
import webpackDev from './webpack-dev'
import webpackHot from './webpack-hot'
import config, {paths} from '../../build/config'
import {clientConfig, serverConfig} from '../../build/webpack'

const readFile = (fs, file) => {
  try {
    return fs.readFileSync(paths.dist(file), 'utf-8')
  } catch (e) {
  }
}

export default (app, templatePath, getTemplate, cb) => {
  let bundle, clientManifest, fs, template
  let ready

  const readyPromise = new Promise(resolve => {
    ready = resolve
  })

  const update = () => {
    if (bundle && clientManifest) {
      ready()
      cb(bundle, {
        fs,
        template,
        clientManifest
      })
    }
  }

  // read template from disk and watch
  template = getTemplate(templatePath)
  chokidar.watch(templatePath).on('change', () => {
    template = getTemplate(templatePath)
    console.log('pug template updated.')
    update()
  })

  clientConfig.entry.push('webpack-hot-middleware/client')

  const clientCompiler = webpack(clientConfig)

  const devMiddleware = webpackDevMiddleware(clientCompiler, {
    publicPath: config.publicPath,
    hot: true,
    quiet: config.quiet,
    noInfo: config.quiet,
    lazy: false,
    stats: config.stats
  })

  clientCompiler.plugin('done', stats => {
    stats = stats.toJson()
    stats.errors.forEach(console.error)
    stats.warnings.forEach(console.warn)
    if (stats.errors.length) return

    fs = devMiddleware.fileSystem
    clientManifest = JSON.parse(readFile(fs, 'vue-ssr-client-manifest.json'))
    update()
  })

  app.use(webpackDev(clientCompiler, devMiddleware))
  app.use(webpackHot(clientCompiler))

  const serverCompiler = webpack(serverConfig)
  const mfs = new MFS()
  serverCompiler.outputFileSystem = mfs
  serverCompiler.watch({}, (err, stats) => {
    if (err) throw err
    stats = stats.toJson()
    if (stats.errors.length) return

    // read bundle generated by vue-ssr-webpack-plugin
    bundle = JSON.parse(readFile(mfs, 'vue-ssr-server-bundle.json'))
    update()
  })

  return readyPromise
}
